"""empty message

Revision ID: 658762df87dd
Revises: f65eb2960792
Create Date: 2019-10-31 15:02:08.380376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658762df87dd'
down_revision = 'f65eb2960792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True, comment='名称'),
    sa.Column('enable', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('is_top', sa.Boolean(), nullable=True, comment='是否是顶级部门'),
    sa.Column('child_department_id', sa.Integer(), nullable=True, comment='下级部门id'),
    sa.ForeignKeyConstraint(['child_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('department_masters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('department_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department_users')
    op.drop_table('department_masters')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
